#Para uso de docker
server.port=8089

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3314/inmobiliaria_reportes_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Chochex1367*}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/