version: '3.8'

services:

  # Base de datos para inmobiliaria-cliente
  mysql-clientes:
    image: mysql:8.0
    container_name: mysql-clientes
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Chochex1367*
      MYSQL_DATABASE: inmobiliaria_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_clientes_data:/var/lib/mysql

  # Cuando agregues más microservicios, cada uno con su propia BD
  # mysql-propiedades:
  #   image: mysql:8.0
  #   container_name: mysql-propiedades
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Chochex1367*
  #     MYSQL_DATABASE: inmobiliaria_propiedades_db
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - mysql_propiedades_data:/var/lib/mysql

volumes:
  mysql_clientes_data:
  # mysql_propiedades_data: