CREATE TABLE propiedad (
idPropiedad BIGINT NOT NULL AUTO_INCREMENT,
titulo VARCHAR(255) NOT NULL,
direccion VARCHAR(255) NOT NULL,
tipo VARCHAR(255) NOT NULL,
precio DOUBLE NOT NULL,
estado BOOLEAN NOT NULL DEFAULT TRUE,
superficie_m2 DOUBLE NOT NULL,
habitaciones INT NOT NULL,
bannos INT NOT NULL,
descripcion TEXT,
PRIMARY KEY (idPropiedad)
);