CREATE TABLE PROPIEDAD (
    IDPROPIEDAD BIGINT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    precio DOUBLE NOT NULL,
    superficie_m2 DOUBLE NOT NULL,
    habitaciones INT NOT NULL,
    baños INT NOT NULL,
    descripcion TEXT
);