server.port=8080
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# inmobiliaria-agente
spring.cloud.gateway.routes[0].id=inmobiliaria-agente
spring.cloud.gateway.routes[0].uri=lb://INMOBILIARIA-AGENTE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/agente/**

# inmobiliaria-cliente
spring.cloud.gateway.routes[1].id=inmobiliaria-cliente
spring.cloud.gateway.routes[1].uri=lb://INMOBILIARIA-CLIENTE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/clientes/**

# inmobiliaria-propiedad
spring.cloud.gateway.routes[2].id=inmobiliaria-propiedad
spring.cloud.gateway.routes[2].uri=lb://INMOBILIARIA-PROPIEDAD
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/propiedad/**

# inmobiliaria-visita
spring.cloud.gateway.routes[3].id=inmobiliaria-visita
spring.cloud.gateway.routes[3].uri=lb://INMOBILIARIA-VISITA
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/visitas/**

# inmobiliaria-contrato
spring.cloud.gateway.routes[4].id=inmobiliaria-contrato
spring.cloud.gateway.routes[4].uri=lb://INMOBILIARIA-CONTRATO
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/contratos/**

# inmobiliaria-pago
spring.cloud.gateway.routes[5].id=inmobiliaria-pago
spring.cloud.gateway.routes[5].uri=lb://INMOBILIARIA-PAGO
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/pagos/**

# inmobiliaria-notificacion
spring.cloud.gateway.routes[6].id=inmobiliaria-notificacion
spring.cloud.gateway.routes[6].uri=lb://INMOBILIARIA-NOTIFICACION
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/notificaciones/**

# inmobiliaria-auth
spring.cloud.gateway.routes[7].id=inmobiliaria-auth
spring.cloud.gateway.routes[7].uri=lb://INMOBILIARIA-AUTH
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/auth/**

# inmobiliaria-reporte
spring.cloud.gateway.routes[8].id=inmobiliaria-reporte
spring.cloud.gateway.routes[8].uri=lb://INMOBILIARIA-REPORTE
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/v1/reporte/**

# inmobiliaria-mantencion
spring.cloud.gateway.routes[9].id=inmobiliaria-mantencion
spring.cloud.gateway.routes[9].uri=lb://INMOBILIARIA-MANTENCION
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/v1/mantencion/**