spring.application.name=api-gateway
# Cambiar para ocupar otras
spring.profiles.active=local

spring.cloud.gateway.discovery.locator.enabled=false

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true