server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# inmobiliaria-agente
spring.cloud.gateway.routes[0].id=inmobiliaria-agente
spring.cloud.gateway.routes[0].uri=lb://INMOBILIARIA-AGENTE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/agente/**

# inmobiliaria_cliente
spring.cloud.gateway.routes[1].id=inmobiliaria-cliente
spring.cloud.gateway.routes[1].uri=lb://INMOBILIARIA-CLIENTE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/clientes/**

# inmobiliaria-propiedad
spring.cloud.gateway.routes[2].id=inmobiliaria-propiedad
spring.cloud.gateway.routes[2].uri=lb://INMOBILIARIA-PROPIEDAD
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/propiedad/**

# inmobiliaria-visita
spring.cloud.gateway.routes[3].id=inmobiliaria-visita
spring.cloud.gateway.routes[3].uri=lb://INMOBILIARIA-VISITA
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/visitas/**

# inmobiliaria-contrato
spring.cloud.gateway.routes[4].id=inmobiliaria-contrato
spring.cloud.gateway.routes[4].uri=lb://INMOBILIARIA-CONTRATO
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/contratos/**

# inmobiliaria-pago
spring.cloud.gateway.routes[5].id=inmobiliaria-pago
spring.cloud.gateway.routes[5].uri=lb://INMOBILIARIA-PAGO
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/pagos/**

# inmobiliaria-notificacion
spring.cloud.gateway.routes[6].id=inmobiliaria-notificacion
spring.cloud.gateway.routes[6].uri=lb://INMOBILIARIA-NOTIFICACION
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/notificaciones/**

# inmobiliaria-auth
spring.cloud.gateway.routes[7].id=inmobiliaria-auth
spring.cloud.gateway.routes[7].uri=lb://INMOBILIARIA-AUTH
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/auth/**

# inmobiliaria-reporte
spring.cloud.gateway.routes[8].id=inmobiliaria-reporte
spring.cloud.gateway.routes[8].uri=lb://INMOBILIARIA-REPORTE
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/v1/reporte/**

# inmobiliaria-mantencion
spring.cloud.gateway.routes[9].id=inmobiliaria-mantencion
spring.cloud.gateway.routes[9].uri=lb://INMOBILIARIA-MANTENCION
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/v1/mantencion/**




#para el Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Registrar cada microservicio como una "fuente" de documentación
springdoc.swagger-ui.urls[0].name=Clientes
springdoc.swagger-ui.urls[0].url=/inmobiliaria-cliente/v3/api-docs

springdoc.swagger-ui.urls[1].name=Propiedades
springdoc.swagger-ui.urls[1].url=/inmobiliaria-propiedad/v3/api-docs

springdoc.swagger-ui.urls[2].name=Agentes
springdoc.swagger-ui.urls[2].url=/inmobiliaria-agente/v3/api-docs

springdoc.swagger-ui.urls[3].name=Visitas
springdoc.swagger-ui.urls[3].url=/inmobiliaria-visita/v3/api-docs

springdoc.swagger-ui.urls[4].name=Contratos
springdoc.swagger-ui.urls[4].url=/inmobiliaria-contrato/v3/api-docs

springdoc.swagger-ui.urls[5].name=Pagos
springdoc.swagger-ui.urls[5].url=/inmobiliaria-pago/v3/api-docs

springdoc.swagger-ui.urls[6].name=Notificaciones
springdoc.swagger-ui.urls[6].url=/inmobiliaria-notificacion/v3/api-docs

springdoc.swagger-ui.urls[7].name=Autenticación
springdoc.swagger-ui.urls[7].url=/inmobiliaria-auth/v3/api-docs

springdoc.swagger-ui.urls[8].name=Reportes
springdoc.swagger-ui.urls[8].url=/inmobiliaria-reporte/v3/api-docs

springdoc.swagger-ui.urls[9].name=Mantenciones
springdoc.swagger-ui.urls[9].url=/inmobiliaria-mantencion/v3/api-docs


# Rutas para exponer el JSON de OpenAPI de cada microservicio

#inmobiliaria-cliente
spring.cloud.gateway.routes[10].id=inmobiliaria-cliente-docs
spring.cloud.gateway.routes[10].uri=lb://INMOBILIARIA-CLIENTE
spring.cloud.gateway.routes[10].predicates[0]=Path=/inmobiliaria-cliente/v3/api-docs
spring.cloud.gateway.routes[10].filters[0]=RewritePath=/inmobiliaria-cliente/v3/api-docs, /v3/api-docs

#inmobiliaria-propiedad
spring.cloud.gateway.routes[11].id=inmobiliaria-propiedad-docs
spring.cloud.gateway.routes[11].uri=lb://INMOBILIARIA-PROPIEDAD
spring.cloud.gateway.routes[11].predicates[0]=Path=/inmobiliaria-propiedad/v3/api-docs
spring.cloud.gateway.routes[11].filters[0]=RewritePath=/inmobiliaria-propiedad/v3/api-docs, /v3/api-docs    

#inmobiliaria-agente
spring.cloud.gateway.routes[12].id=inmobiliaria-agente-docs
spring.cloud.gateway.routes[12].uri=lb://INMOBILIARIA-AGENTE
spring.cloud.gateway.routes[12].predicates[0]=Path=/inmobiliaria-agente/v3/api-docs
spring.cloud.gateway.routes[12].filters[0]=RewritePath=/inmobiliaria-agente/v3/api-docs, /v3/api-docs

#inmobiliaria-visita
spring.cloud.gateway.routes[13].id=inmobiliaria-visita-docs
spring.cloud.gateway.routes[13].uri=lb://INMOBILIARIA-VISITA
spring.cloud.gateway.routes[13].predicates[0]=Path=/inmobiliaria-visita/v3/api-docs
spring.cloud.gateway.routes[13].filters[0]=RewritePath=/inmobiliaria-visita/v3/api-docs, /v3/api-docs

#inmobiliaria-contrato
spring.cloud.gateway.routes[14].id=inmobiliaria-contrato-docs
spring.cloud.gateway.routes[14].uri=lb://INMOBILIARIA-CONTRATO
spring.cloud.gateway.routes[14].predicates[0]=Path=/inmobiliaria-contrato/v3/api-docs
spring.cloud.gateway.routes[14].filters[0]=RewritePath=/inmobiliaria-contrato/v3/api-docs, /v3/api-docs

#inmobiliaria-pago
spring.cloud.gateway.routes[15].id=inmobiliaria-pago-docs
spring.cloud.gateway.routes[15].uri=lb://INMOBILIARIA-PAGO
spring.cloud.gateway.routes[15].predicates[0]=Path=/inmobiliaria-pago/v3/api-docs
spring.cloud.gateway.routes[15].filters[0]=RewritePath=/inmobiliaria-pago/v3/api-docs, /v3/api-docs

#inmobiliaria-notificacion
spring.cloud.gateway.routes[16].id=inmobiliaria-notificacion-docs
spring.cloud.gateway.routes[16].uri=lb://INMOBILIARIA-NOTIFICACION
spring.cloud.gateway.routes[16].predicates[0]=Path=/inmobiliaria-notificacion/v3/api-docs
spring.cloud.gateway.routes[16].filters[0]=RewritePath=/inmobiliaria-notificacion/v3/api-docs, /v3/api-docs

#inmobiliaria-auth
spring.cloud.gateway.routes[17].id=inmobiliaria-auth-docs
spring.cloud.gateway.routes[17].uri=lb://INMOBILIARIA-AUTH
spring.cloud.gateway.routes[17].predicates[0]=Path=/inmobiliaria-auth/v3/api-docs
spring.cloud.gateway.routes[17].filters[0]=RewritePath=/inmobiliaria-auth/v3/api-docs, /v3/api-docs

#inmobiliaria-reporte
spring.cloud.gateway.routes[18].id=inmobiliaria-reporte-docs
spring.cloud.gateway.routes[18].uri=lb://INMOBILIARIA-REPORTE
spring.cloud.gateway.routes[18].predicates[0]=Path=/inmobiliaria-reporte/v3/api-docs
spring.cloud.gateway.routes[18].filters[0]=RewritePath=/inmobiliaria-reporte/v3/api-docs, /v3/api-docs

#inmobiliaria-mantencion
spring.cloud.gateway.routes[19].id=inmobiliaria-mantencion-docs
spring.cloud.gateway.routes[19].uri=lb://INMOBILIARIA-MANTENCION
spring.cloud.gateway.routes[19].predicates[0]=Path=/inmobiliaria-mantencion/v3/api-docs
spring.cloud.gateway.routes[19].filters[0]=RewritePath=/inmobiliaria-mantencion/v3/api-docs, /v3/api-docs

