spring.application.name=inmobiliaria-eureka
server.port=8761

# Estas líneas evitan que el servidor intente registrarse a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=localhost
eureka.server.enable-self-preservation=false
spring.cloud.compatibility-verifier.enabled=false