CREATE TABLE casa (
id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
sku           VARCHAR2(50) NOT NULL,
titulo        VARCHAR2(100) NOT NULL,
direccion     VARCHAR2(300) NOT NULL,
descripcion   VARCHAR2(1000) NOT NULL,
ciudad        VARCHAR2(100) NOT NULL,
comuna        VARCHAR2(100) NOT NULL,
precio        NUMBER(19, 2) NOT NULL,
estado        VARCHAR2(20) DEFAULT 'DISPONIBLE',
fecha_venta   DATE,
correo_casa   VARCHAR2(150) NOT NULL,
CONSTRAINT pk_casa PRIMARY KEY (id),
CONSTRAINT uk_casa_sku UNIQUE (sku)
);