CREATE TABLE MANTENCION (
    IDMANTENCION    BIGINT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION     TEXT,
    ESTADO          VARCHAR(50) NOT NULL,
    Fecha_inicio    DATE NOT NULL,
    Fecha_fin       DATE,
    IDAGENTE        BIGINT NOT NULL,
    IDPROPIEDAD     BIGINT NOT NULL
);