server:
  port: 8080

spring:
  application:
    name: inmobiliaria-gateway

  cloud:
    gateway:
      # Descubrimiento automático via Eureka
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # Rutas manuales por microservicio
      routes:
        - id: cliente-service
          uri: lb://inmobiliaria_cliente  
          predicates:
            - Path=/api/v1/clientes/**

        # Cuando agregues más microservicios, los añades aquí:
        # - id: propiedad-service
        #   uri: lb://inmobiliaria-propiedad
        #   predicates:
        #     - Path=/api/v1/propiedades/**

# Registro en Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Logs para ver qué rutas está procesando
logging:
  level:
    org.springframework.cloud.gateway: DEBUG